# Generated by Django 2.1.5 on 2019-02-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.IntegerField()),
                ('animal_word', models.CharField(max_length=15)),
                ('animal_pic', models.ImageField(upload_to='')),
                ('animal_audio', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
