# Generated by Django 2.1.5 on 2019-02-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='animal_word',
            new_name='animal_name',
        ),
    ]
