# Generated by Django 2.1.5 on 2019-02-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barnamala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barna',
            name='barna_letter',
            field=models.CharField(default='', max_length=1),
        ),
    ]
