# Generated by Django 2.1.5 on 2019-02-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbers',
            name='num_audio',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
