# Generated by Django 2.1.5 on 2019-02-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha_id', models.IntegerField()),
                ('alpha_word', models.CharField(max_length=15)),
                ('alpha_gif', models.ImageField(upload_to='')),
                ('word_gif', models.ImageField(upload_to='')),
            ],
        ),
    ]
