# Generated by Django 2.1.5 on 2019-02-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_alphabets_word_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alphabets',
            name='alpha_letter_lower',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='alphabets',
            name='alpha_letter_upper',
            field=models.CharField(default='', max_length=1),
        ),
    ]
