# Generated by Django 2.1.5 on 2019-02-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.IntegerField()),
                ('color_name', models.CharField(max_length=15)),
                ('color_pic', models.ImageField(upload_to='')),
                ('color_audio', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
